name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'client/**'
      - 'server/**'
      - '.github/workflows/build.yml'
      - '.github/workflows/server-build.yml'
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-server:
    uses: ./.github/workflows/server-build.yml

  lint-client:
    name: Lint Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install Dependencies
        run: |
          cd client
          npm install

      - name: Lint
        run: |
          cd client
          npm run lint

  package-extension:
    name: Package Extension
    needs: [build-server, lint-client]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install Dependencies
        run: |
          cd client
          npm install

      - name: Download Server Binaries
        uses: actions/download-artifact@v8
        with:
          path: bin-stage
          pattern: hom-lsp-*

      - name: Finalize Binary Names
        run: |
          mkdir -p client/server-bin
          cp bin-stage/hom-lsp-linux-amd64/hom-lsp client/server-bin/hom-lsp-linux-amd64
          cp bin-stage/hom-lsp-win-amd64.exe/hom-lsp.exe client/server-bin/hom-lsp-win-amd64.exe
          cp bin-stage/hom-lsp-macos-arm64/hom-lsp client/server-bin/hom-lsp-macos-arm64
          chmod +x client/server-bin/hom-lsp-linux-amd64 client/server-bin/hom-lsp-macos-arm64

      - name: Copy Resources
        run: |
          mv README.md client/README.md
          mv CHANGELOG.md client/CHANGELOG.md

      - name: Package VSIX
        run: |
          cd client
          npm run compile
          npx vsce package -o ../hearts-of-modding.vsix

      - name: Upload VSIX
        uses: actions/upload-artifact@v7
        with:
          name: extension-vsix
          path: hearts-of-modding.vsix
